=== Dancikowski/citizens-app/xml/zadanie1/wydzialy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="wydzialy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="wydzial" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="wydzial">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nazwa"/>
                <xs:element ref="adresyuczelni"/>
                <xs:element ref="pracownicy"/>
                <xs:element ref="przedmioty"/>
            </xs:sequence>
            <xs:attribute name="wydzial-id" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="pracownicy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pracownik" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pracownik">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="imie"/>
                <xs:element ref="nazwisko"/>
                <xs:element ref="kategoria"/>
                <xs:element ref="tytul" minOccurs="0" />
                <xs:element ref="adresypracownika"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="przedmioty">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="przedmiot" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="przedmiot">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nazwa"/>
                <xs:element ref="opis"/>
                <xs:element ref="prowadzacy"/>
                <xs:element ref="iloscuczniow" />
            </xs:sequence>
            <xs:attribute name="przedmiot-id" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="opis" type="xs:string"/>
    <xs:element name="prowadzacy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pojedynczyprowadzacy" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Simple types -->
    <xs:element name="nazwa" type="xs:string"/>
    <xs:element name="adres" type="xs:string"/>
    <xs:element name="imie" type="xs:string"/>
    <xs:element name="nazwisko" type="xs:string"/>
    <xs:element name="tytul" type="xs:string" />

    <xs:element name="pojedynczyprowadzacy">
        <xs:complexType>
            <xs:attribute name="idref" use="required" type="xs:IDREF"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="adresyuczelni">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="adres"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="adresypracownika">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="adrespracownika"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="adrespracownika">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ulica" type="xs:string" />
                <xs:element name="numer" type="xs:integer" />
                <xs:element name="kod" type="xs:string" />
                <xs:element name="miejscowosc" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="kategoria">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="naukowy"/>
                <xs:enumeration value="adnministracyjny"/>
                <xs:enumeration value="techniczny"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="iloscuczniow">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="4"/>
                <xs:maxInclusive value="500"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== Dancikowski/citizens-app/xml/zadanie1/wydzialy.xml
<wydzialy  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="wydzialy.xsd">
    <wydzial wydzial-id="wmi">
        <nazwa>Wydzial Matematyki i Informatyki</nazwa>
        <adresyuczelni>
            <adres>Umultowska 1</adres>
            <adres>Umultowska 2</adres>
        </adresyuczelni>
        <pracownicy>
            <pracownik id="id-1">
                <imie>Bartosz</imie>
                <nazwisko>Mejwski</nazwisko>
                <kategoria>adnministracyjny</kategoria>
                <adresypracownika>
                    <adrespracownika>
                        <ulica>Rozana</ulica>
                        <numer>123</numer>
                        <kod>123-123</kod>
                        <miejscowosc>Poznan</miejscowosc>
                    </adrespracownika>
                </adresypracownika>
            </pracownik>
            <pracownik id="id-3">
                <imie>Damian</imie>
                <nazwisko>Stanowski</nazwisko>
                <kategoria>techniczny</kategoria>
                <adresypracownika>
                    <adrespracownika>
                        <ulica>Wrocławska</ulica>
                        <numer>123</numer>
                        <kod>213-123</kod>
                        <miejscowosc>Warszawa</miejscowosc>
                    </adrespracownika>
                </adresypracownika>
            </pracownik>
        </pracownicy>
        <przedmioty>
            <przedmiot przedmiot-id="mat-1">
                <nazwa>Matematyka dyskretna</nazwa>
                <opis>To jest opis przedmiotu Matematyka dyskretna</opis>
                <prowadzacy>
                    <pojedynczyprowadzacy idref="id-1" />
                    <pojedynczyprowadzacy idref="id-3" />
                </prowadzacy>
                <iloscuczniow>123</iloscuczniow>
            </przedmiot>
            <przedmiot przedmiot-id="mat-2">
                <nazwa>Java</nazwa>
                <opis>To jest opis przedmiotu Java</opis>
                <prowadzacy>
                    <pojedynczyprowadzacy idref="id-1" />
                </prowadzacy>
                <iloscuczniow>123</iloscuczniow>
            </przedmiot>
        </przedmioty>
    </wydzial>
    <wydzial wydzial-id="wnpid">
        <nazwa>Wydzial Nauk Politycznych i Dziennikarstwa</nazwa>
        <adresyuczelni>
            <adres>Różana 21</adres>
            <adres>Umultowska 123</adres>
        </adresyuczelni>
        <pracownicy>
            <pracownik id="pd-1">
                <imie>Damian</imie>
                <nazwisko>Szkolnikowski</nazwisko>
                <kategoria>naukowy</kategoria>
                <adresypracownika>
                    <adrespracownika>
                        <ulica>Murawa</ulica>
                        <numer>12</numer>
                        <kod>21-12</kod>
                        <miejscowosc>Kraków</miejscowosc>
                    </adrespracownika>
                </adresypracownika>
            </pracownik>
        </pracownicy>
        <przedmioty>
            <przedmiot przedmiot-id="pol-1">
                <nazwa>Prawo</nazwa>
                <opis>To jest opis przedmotu prawo</opis>
                <prowadzacy>
                    <pojedynczyprowadzacy idref="pd-1" />
                </prowadzacy>
                <iloscuczniow>123</iloscuczniow>
            </przedmiot>
            <przedmiot przedmiot-id="pol-2">
                <nazwa>Język Angielski</nazwa>
                <opis>Opis przedmiotu Język Angielski</opis>
                <prowadzacy>
                    <pojedynczyprowadzacy idref="pd-1" />
                </prowadzacy>
                <iloscuczniow>123</iloscuczniow>
            </przedmiot>
        </przedmioty>
    </wydzial>
</wydzialy>
